# Generated by Django 5.1.6 on 2025-03-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occurrence_date', models.DateField()),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.club')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ongoing_activities_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('annual_parties_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club_management.club')),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club_management.club')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(auto_now_add=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('General', 'General Member'), ('Leader', 'Executive Leader')], default='General', max_length=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.student')),
            ],
        ),
    ]
