# Generated by Django 5.1.6 on 2025-03-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
